### ISSUE TITLE
iPhone App rejection because of private API _isKVOA

### ISSUE THREAD

**Issue by steipete** [mikeash/MAZeroingWeakRef#1]
Hi Mike,

our app got rejected because this uses _isKVOA, even on COREFOUNDATION_HACK_LEVEL 0. 

Is there any way to change this class to _not_ use this IsKVOSubclass methode?

cheers,
Peter

**Comment by cahlbin** [comment]
I actually got a rejected due to this as well, and made the following quick n dirty change

static BOOL IsKVOSubclass(id obj)
{  
  if(!obj)
    return NO;

  Class clazz = object_getClass(obj);
  NSString \* clazzName = NSStringFromClass(clazz);

  return [clazzName hasPrefix:@"NSKVO"];

}

Makes the current KVO test case pass, but it's not really a good solution I'd say.

**Comment by mikeash** [comment]
Argh. That's no fun.

A slightly better way to check might be this:

```
return [obj class] == class_getSuperclass(object_getClass(obj));
```

This relies on the fact that KVO objects fake out `-class` to return the original class rather than the KVO subclass.

**Comment by steipete** [comment]
mike, 

thanks for the quick answer. Your workaround works perfect, I'll resubmit tomorrow.
I pushed the changes to my fork, https://github.com/steipete/MAZeroingWeakRef

cheers,
Peter

**Comment by mikeash** [comment]
No problem. Sorry for the trouble.

I've added this code, plus a new `KVO_HACK_LEVEL` macro to my version of the project which lets you easily switch between the private method and the class check.
